{{- if and .Values.persistence.database.enabled (not .Values.persistence.database.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "home-information.fullname" . }}-database
  labels:
    {{- include "home-information.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.database.accessMode }}
  {{- with .Values.persistence.database.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.database.size }}
{{- end }}
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "home-information.fullname" . }}-media
  labels:
    {{- include "home-information.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  {{- with .Values.persistence.media.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
{{- end }}
